# Generated by Django 2.2.7 on 2019-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_curency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curency',
            name='curency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curency',
            name='etebar',
            field=models.CharField(blank=True, default=models.IntegerField(default=0), max_length=200),
        ),
        migrations.AlterField(
            model_name='curency',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
