# Generated by Django 2.2.7 on 2019-11-23 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Added',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_total', models.DecimalField(decimal_places=1, max_digits=20)),
                ('product_photo', models.ImageField(upload_to='cart/products/%Y/%m/%d/')),
                ('addtocart_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ordering', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
