# Generated by Django 2.2.7 on 2019-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_added',
            name='product_size',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
