# Generated by Django 2.2.7 on 2019-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_added_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_added',
            name='key_del',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
