# Generated by Django 2.2.7 on 2019-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_added_key_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_added',
            name='key_del',
            field=models.CharField(max_length=500),
        ),
    ]
