# Generated by Django 2.2.7 on 2019-11-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191126_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_added',
            name='key_del',
        ),
    ]
