# Generated by Django 2.2.7 on 2019-11-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='size1',
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
